<a href="https://colab.research.google.com/github/Karthikraja131/Data-Science-AI-Engineer-Interview-/blob/main/Interview_programes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a program to reverese a string.

In [ ]:
def reverse_string(string):
  return string[::-1]

string = input("Enter a String:  ")
reverse_char = reverse_string(string)
print(reverse_char)

Enter a String:  karthik
kihtrak

2. Write a program to reverese a string without using any string built in reversal functions.

In [ ]:
def reverse_string(input_string):
  reverse_str = ""
  for char in input_string:
    reverse_str= char + reverse_str
  return reverse_str

string =input("Enter a String:")
reverse_char = reverse_string(string)
print(reverse_char)

Enter a String:Hello Universe!!
!!esrevinU olleH

In [ ]:
def reverse_string(input_string):
  reverse_str = ""
  for char in input_string:
    reverse_str= char + reverse_str
  return reverse_str

string = """Enter a String:
hi how this is Python Programme
I wished to do Python and Artificial Intelligence  """
reverse_char = reverse_string(string)
print(reverse_char)

  ecnegilletnI laicifitrA dna nohtyP od ot dehsiw I
emmargorP nohtyP si siht woh ih
:gnirtS a retnE

3. Write the Program to check the given string is Palindrome.

* A palindrome is a word, phrase, number, or other sequence of characters that reads the same backward as forward. Examples include "racecar," "level," and "madam."

In [ ]:
def Is_Panlindrome(string):
  if string == string[::-1]:
    return "The given string is Palindrome "
  else:
    return "The given string is not a Panlindrome"

string = input("Enter a String:  ")
palindrome = Is_Panlindrome(string)
print(palindrome)

Enter a String:  tenanet
The given string is Palindrome

In [ ]:
def Is_Panlindrome(string):
  string = string.lower().strip()
  print(string)
  return string == string[::-1]

string = "  Tenet "
palindrome = Is_Panlindrome(string)
print(palindrome)

tenet
True

4. 4. By Bool response

In [ ]:
def Is_Panlindrome(string):
  string = string.replace(" ","").lower()
  return string == string[::-1]


string = input("Enter a String:  ")
palindrome = Is_Panlindrome(string)
print(palindrome)

Enter a String:  level
True

5.Write a program to find the largest number in the given list

In [ ]:
def find_largest_number(given_list):
  sorted_list = sorted(given_list,reverse=True)
  return sorted_list[0]

user_value = input(("Enter a Number:  ")).split(",")
given_list=list(user_value)
given_list=[int(x) for x in uset_value]
print(given_list)
find_largest_number(given_list)

Enter a Number:  10,20,30,52,10,1,20,100
[10, 20, 30, 52, 10, 1, 20, 100]

100

In [ ]:
def largest_number(lst):
  sorted_list = sorted(lst,reverse= True)
  print(sorted_list)
  return sorted_list[0]

lst = [1,2,3,4]
print(largest_number(lst))

[4, 3, 2, 1]
4

In [ ]:
def find_largest_number(given_list):
  given_list.sort(reverse = True)
  return given_list[0]

user_value = (input(("Enter only nuber with seperation of comma:  "))).split(",")
given_list=[int(x) for x in user_value]
print(given_list)
find_largest_number(given_list)

Enter only nuber with seperation of comma:  6,1,4,5
[6, 1, 4, 5]

6

In [ ]:
def find_largest_number(given_list):
  if len(given_list)<1:
    return None

  large_number =given_list[0]
  for element in given_list:
    if element > large_number:
      large_number = element
  return large_number

user_value = (input(("Enter only nuber with seperation of comma:  "))).split(",")
given_list=[int(x) for x in user_value]
print(given_list)
find_largest_number(given_list)

Enter only nuber with seperation of comma:  10,20,30,52,10,1,20,15
[10, 20, 30, 52, 10, 1, 20, 15]

52

6. Implement a function to count occurrence of each element in a list.

> Add blockquote

In [ ]:
def count_occurrences(lst):
  occurences={}
  for element in lst:
    if element in occurences:
      occurences[element] +=1
    else:
      occurences[element] = 1
  return occurences

lst = [1,1,1,2,2,3,5,4,7,7]
print(count_occurrences(lst))

{1: 3, 2: 2, 3: 1, 5: 1, 4: 1, 7: 2}

7. Write a Python Program to find the second largest number in a list.

In [ ]:
def second_largest_number(lst):
  if len(lst) < 2:
    return None

  first_larger = max(lst[0], lst[1])
  second_larger = min(lst[0], lst[1])

  for x in range(2, len(lst)):
    if lst[x] > first_larger:
      second_larger = first_larger
      first_larger = lst[x]
    elif lst[x] > second_larger and lst[x] != first_larger:
      second_larger = lst[x]

  return second_larger

lst = [20, 10, 8, 12, 5, 3, 1, 20, 15]
print(second_largest_number(lst))

15

In [ ]:
# Second largest number

def second_largest(list):
  if len(list)<2:
    return None

  large = sec = float('-inf')

  for i in list:
    if i > large:
      sec = large
      large = i
    elif i > sec and i != large:
      sec = i

  return sec
list = [20, 10, 8, 12, 5, 3, 1, 20, 15, 15,18]
print(second_largest(list))

18

### Find the Second Least value

In [ ]:
def second_least(list):
  if len(list) < 2:
    return None

  first = sec = float('inf')
  for i in list:
    if i < first:
      sec = first
      first = i

    elif i < sec and i != first:
      sec = i
  return sec #if sec != float('inf') else None

list = [1,2,3,4,5]
print(second_least(list))

2

### get minimum and maximum marks

In [ ]:
# get minimum and maximum marks
students=[['Harry',37.21],['Berry',37.21],['Tina',37.2],['Akriti', 41],['Harsh', 39]]
type(students)
min_mark = min(students, key = lambda x : x[1])
max_mark = max(students, key = lambda x : x[1])
print(min_mark)
print(max_mark)

['Tina', 37.2]
['Akriti', 41]

In [ ]:
# Create DF
import pandas as pd
students=[['Harry',37.21],['Berry',37.21],['Tina',37.2],['Akriti', 41],['Harsh', 39]]
df = pd.DataFrame(students)
df

        0      1
0   Harry  37.21
1   Berry  37.21
2    Tina  37.20
3  Akriti  41.00
4   Harsh  39.00

###X= (A/avg(A,B,C)) using pandas.
data={'A': [1,2,3], 'B': [4,5,6],'C': [7,8,9]}

In [ ]:
data={'A': [1,2,3], 'B': [4,5,6],'C': [7,8,9]}
import pandas as pd
df = pd.DataFrame(data)
df['avg'] = df[['A','B','C']].mean(axis=1)
df['X'] = df['A']/df['avg']
df

   A  B  C  avg     X
0  1  4  7  4.0  0.25
1  2  5  8  5.0  0.40
2  3  6  9  6.0  0.50

### Find the length

In [ ]:
input=["Tina", "Raj","Tom"]
length_string = [len(x) for x in input]
length_string

[4, 3, 3]

###  Find the two index that , sum of the Target

In [ ]:
#
def find_sum_index(lst, target):
  seen ={}
  for i, num in enumerate(lst):
    diff = target - num
    if diff in seen:
      return [seen[diff], i]
    else:
      seen[num] = i
  return []

lst = [1,2,3,4,5,6,7]
target =5
print(find_sum_index(lst, target))

[1, 2]

### To  print the substring the given string from starting 2 char

In [ ]:
def sub_string(string):
  sub_string = []
  l = len(string)
  for i in range(2, l):

    for j in range(l-i+1):
      sub =string[j: j+i]
      sub_string.append(sub)
  return sub_string
string = 'banana'
print(sub_string(string))

['ba', 'an', 'na', 'an', 'na', 'ban', 'ana', 'nan', 'ana', 'bana', 'anan', 'nana', 'banan', 'anana']

In [ ]:
# without function
string = 'banana'
l = len(string)

# Iterate over all possible substring lengths (starting from 2)
for i in range(2,l):
    # Iterate over all starting indices for substrings of this length
    for j in range(l - i+1):
        sub_str = string[j:j + i]
        print(sub_str)

ba
an
na
an
na
ban
ana
nan
ana
bana
anan
nana
banan
anana

In [ ]:
s = 'banana'
n = len(s)

s_ind = 2
while s_ind < n:
    i = 0
    while i <= n - s_ind:
        print(s[i:i+s_ind])
        i += 1
    s_ind += 1

ba
an
na
an
na
ban
ana
nan
ana
bana
anan
nana
banan
anana

### Interleave_strings
Input: str1 = "abcd", str2 = "1234"  
Output: "1a2b3c4d"

Input: str1 = "Google", str2 = "1234"  
Output: "1G2o3o4gle"

In [ ]:
def interleave_strings(str1, str2):
  result = []
  min_len = min(len(str1), len(str2))

  for i in range(min_len):
    result.append(str2[i])
    result.append(str1[i])

  if len(str1) > len(str2):
    result.extend(str1[min_len:])
  elif len(str2) > len(str1):
    result.extend(str2[min_len:])
  return ''.join(result)

str1 = "abcd"
str2 = "1234"
str3 = "Google"
str4 = "1234"
print(interleave_strings(str1, str2))
print(interleave_strings(str3, str4))

1a2b3c4d
1G2o3o4gle

### Swapping:
d={'a':1, 'b':2, 'c':1,'d':2, 'e':3}

out={1:('a','c'), 2:('b','d'), 3:'e'}

In [ ]:
d={'a':1, 'b':2, 'c':1,'d':2, 'e':3}

out ={}
for key, value in d.items():
  if value not in out:
    out[value] = []
  out[value].append(key)
print(out)
# Convert lists to tuples if there's more than one element, or keep as string if single
for key, value in out.items():
  if len(value) ==1:
    out[key] = value[0]
  else:
    out[key] = tuple(value)

print(out)
#out={1:('a','c'), 2:('b','d'), 3:'e'}

{1: ['a', 'c'], 2: ['b', 'd'], 3: ['e']}
{1: ('a', 'c'), 2: ('b', 'd'), 3: 'e'}

In [ ]:
d={'a':1, 'b':2, 'c':1,'d':2, 'e':3}
out = {}
for key, value in d.items():
  out.setdefault(value,[]).append(key)
for key, value in out.items():
  if len(value) ==1:
    outmjnhhbgtm
    out[key] = tuple(value)

print(out)

{1: ('a', 'c'), 2: ('b', 'd'), 3: 'e'}

In [ ]:
# output =
d={'a':1, 'b':2, 'c':1,'d':2, 'e':3}
output = {}
for key,value in d.items():
  if value not in output:
    output[value] = []
  output[value].append(key)
print(output)

{1: ['a', 'c'], 2: ['b', 'd'], 3: ['e']}

In [ ]:
#swapping
d={'a':1, 'b':2, 'c':1,'d':2, 'e':3}
output = {}
for key,value in d.items():
  output[value] = key
output

'''A one-to-one swap without data loss is not possible in a normal Python dict if values are not unique.
Because:

Dictionary keys must be unique.

When two different keys ('a' and 'c') have the same value (1), only one of them can survive as a new key in the swapped dictionary.
'''

{1: 'c', 2: 'd', 3: 'e'}

In [ ]:
out = {}
help(out.setdefault)

Help on built-in function setdefault:

setdefault(key, default=None, /) method of builtins.dict instance
    Insert key with a value of default if key is not in the dictionary.

    Return the value for key if key is in the dictionary, else default.

### create the pandas DataFrame

In [ ]:
import pandas as pd
d={'a':1, 'b':2, 'c':1,'d':2, 'e':3}

df = pd.DataFrame(d.items())
df

   0  1
0  a  1
1  b  2
2  c  1
3  d  2
4  e  3

In [ ]:
import pandas as pd
d={'a':1, 'b':2, 'c':1,'d':2, 'e':3}

df = pd.DataFrame(list(d.items()), columns =['key','value'])
df

  key  value
0   a      1
1   b      2
2   c      1
3   d      2
4   e      3

In [ ]:
import pandas as pd
data = {'a':[1,2,3,4], 'b':[5,6,7,8]}
df = pd.DataFrame(data)
print(df)

   a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [ ]:
import pandas as pd

list1 = [1,2,3]
list2 = [4,5,6]

df = pd.DataFrame( list1, columns =['a'])
print(df)

   a
0  1
1  2
2  3

###  Remove the duplicates

In [ ]:
list = [1,2,3,3,2,4,5]
unique = []
for i in list:
    if i not in unique:
        unique.append(i)
print(unique)

[1, 2, 3, 4, 5]

### To find max score by each subject and each student

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Alice', 'Bob', 'Charlie', 'Alice'],
    'subject': ['Math', 'Math', 'Science', 'Science', 'Math', 'English'],
    'score':[90, 80, 85, 85, 100, 70]

})
df

      name  subject  score
0    Alice     Math     90
1      Bob     Math     80
2    Alice  Science     85
3      Bob  Science     85
4  Charlie     Math    100
5    Alice  English     70

In [ ]:
#1. Max Score by Subject

max_score = df.groupby(['subject'])['score'].max().reset_index()
max_score

   subject  score
0  English     70
1     Math    100
2  Science     85

In [ ]:
#2. Max Score by Student
max_score_student = df.groupby(['name'])['score'].max().reset_index()
max_score_student

      name  score
0    Alice     90
1      Bob     85
2  Charlie    100

In [ ]:
 #Max Score by Each Student per Subject
max_by_student_subject  = df.groupby(['name','subject'])['score'].max()
max_by_student_subject

name     subject
Alice    English     70
         Math        90
         Science     85
Bob      Math        80
         Science     85
Charlie  Math       100
Name: score, dtype: int64

In [ ]:
 #Max Score by Each Student per Subject
max_by_student_subject  = df.groupby(['name','subject'])['score'].max().reset_index()
max_by_student_subject

      name  subject  score
0    Alice  English     70
1    Alice     Math     90
2    Alice  Science     85
3      Bob     Math     80
4      Bob  Science     85
5  Charlie     Math    100

### Flatten a list like [[1, 2], [3, 4], [5]] into [1, 2, 3, 4, 5]

In [ ]:
list = [[1, 2], [3, 4], [5]]

flattened_list= []
for sub_list in list:
  for i in sub_list:
    if i not in flattened_list:
      flattened_list.append(i)
print(flattened_list)

[1, 2, 3, 4, 5]

In [ ]:
list = [[1, 2], [3, 4], [5]]
flattened = []
for i in list:
  flattened.extend(i)
flattened

[1, 2, 3, 4, 5]

### To sort the list without inbuiltins

In [ ]:
l = [2,3,1,5,4]
sortlist = []
for i in l:
  inserted = False
  for j in range(len(sortlist)):
    if i < sortlist[j]:
      sortlist.insert(j,i)
      inserted = True
      break
  if  inserted == False:
    sortlist.append(i)
print(sortlist)

[1, 2, 3, 4, 5]

In [ ]:
l = [2,3,1,5,4]
sortlist = []
for i in l:
  inserted = False
  for j in range(len(sortlist)):
    if i < sortlist[j]:
      sortlist.insert(j,i)
      inserted = True
      break
  if not inserted:
    sortlist.append(i)
print(sortlist)

[1, 2, 3, 4, 5]

### To find the right leaders

Input= [16, 17, 4, 3, 5, 2]

Output= [17, 5, 2]

In [ ]:
input= [16, 17, 4, 3, 5, 2]
max_right_value = float('-inf')
leader = []
for i in range(len(input)-1, -1,-1):
  if input[i] > max_right_value:
    leader.insert(0, input[i])
    max_right_value = input[i]
print(leader)

[17, 5, 2]

### list combined
a = [1,2,3]

b= [4,5,6]

output = [[1,4],[2,5],[3,6]]

In [ ]:
a = [1,2,3]
b= [4,5,6]
combined_list = [[i,j] for i, j in zip(a,b)]
combined_list

[[1, 4], [2, 5], [3, 6]]

In [ ]:
a = [1,2,3]
b= [4,5,6]
combined_list=[]
for i, j in zip(a,b):
  combined_list.append([i,j])
combined_list

[[1, 4], [2, 5], [3, 6]]

In [10]:
a= [1,2,3]
b=[4,5,6]
c=[7,8,9]
comb_lst= [[i,j,k] for i,j,k in zip(a,b,c)]
comb_lst

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]